# This rule is not used by the project vuln-patcher itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over vulpatcher.kubewarden.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vuln-patcher
    app.kubernetes.io/managed-by: kustomize
  name: patchjob-admin-role
rules:
- apiGroups:
  - vulpatcher.kubewarden.io
  resources:
  - patchjobs
  verbs:
  - '*'
- apiGroups:
  - vulpatcher.kubewarden.io
  resources:
  - patchjobs/status
  verbs:
  - get
