# This rule is not used by the project vuln-patcher itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to vulpatcher.kubewarden.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vuln-patcher
    app.kubernetes.io/managed-by: kustomize
  name: patchjob-viewer-role
rules:
- apiGroups:
  - vulpatcher.kubewarden.io
  resources:
  - patchjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vulpatcher.kubewarden.io
  resources:
  - patchjobs/status
  verbs:
  - get
